// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccwpwlqrlijtdhhxmxmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjd3B3bHFybGlqdGRoaHhteG1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjU1MTcsImV4cCI6MjA2MDE0MTUxN30.vbSzVlpkZLh1Nqvn_YgM6ryF_dOUP1HMiza3jl0GRgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);